sudo: required

services:
  - docker
  - docker-compose

install:
  - docker-compose build

script:
  - docker start dplpdocker_corenlp_1
  - docker run --net host --entrypoint=/bin/bash -ti dplpdocker_dplp -c py.test test_dplp.py
