sudo: required

services:
  - docker

install:
  - docker build -t dplp .

script:
  - docker run -d -p 9000:9000 -ti nlpbox/corenlp:3.9.2
  - docker run --net host --entrypoint=/bin/bash -ti dplp -c py.test test_dplp.py
