sudo: required

#language: python
#python:
#  - "2.7"

services:
  - docker

#before_install:
install:
  - docker build -t dplp .

script:
  - docker run --entrypoint=/bin/bash -ti dplp -c py.test test_dplp.py
#  - docker ps -a

# command to install dependencies
#install:
#  - pip install pytest sh


# command to run tests
#script:
#  - py.test test_dplp.py
